### ISSUE TITLE
Dúvidas...

### ISSUE THREAD

**Issue by PauloBoaventura** [jhonystein/correios#2]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by soujhony** [comment]
O código, conforme você pode observar, esta em NodeJS. Mas por ser uma API Rest, pode ser utilizando por qualquer plataforma (inclusive PHP, indiferente da versão). 
Utilizei para implementação da consulta de CEP e de Rastreio, um crowler, diretamente da página dos correios, esta até o momento funcionando muito bem, já a parte de frete, esta implementada sobre um webservice SOAP disponibilizado pelos correios. Sobre normas ou padrões, não cheguei a conferir, se puder me dar mais detalhes, posso verificar. 
Sobre o uso, este webservice, assim como a biblioteca criada para sua implementação são de uso livre e irrestrito, conforme licença aplicada (MIT). 

Fique a vontade para copiar, modificar, publicar seu próprio serviço e estarei disponível para eventuais problemas que encontrar.

Caso as informações foram suficientes para você, favor fechar o ticket ;-)

**Comment by PauloBoaventura** [comment]
Olá @jhonystein obrigado por responder prontamente minha dúvida.
O que venho enfrentando é para integrar algo eficiente sobre CEP no Magento 1.9 ou 2.1
Sabe como utilizar e enviar para anexar junto ao pedido?

Agradeço desde já qualquer ajuda!

**Comment by soujhony** [comment]
@PauloBoaventura, desconheço Magento e acredito que não possa lhe ajudar com esse tipo de informação.
